### ISSUE TITLE
do link problem 

### ISSUE THREAD

**Issue by HankerSia** [AutodeskRoboticsLab/RLRoboticAssembly#1]
In step 3, Do you mean i need create a folder on home directory or other place?
And edit line 46 with replacing "local path" with the path of new rllib?
`Traceback (most recent call last):
  File "setup-dev.py", line 46, in <module>
    do_link("rllib", force=args.yes, local_path="/home/kai/")
  File "setup-dev.py", line 22, in do_link
    assert os.path.isdir(local_home), local_home
AssertionError: /home/rllib`
and i tried to replace it with path of ray, 
`do_link("rllib", force=args.yes, local_path="/home/kai/ray/")`
While when i did it, an error occurred. it is shown in the following:
`This will replace:
  /home/kai/anaconda3/envs/tf_torch/lib/python3.7/site-packages/ray/rllib
with a symlink to:
  /home/kai/rllib [Y/n]: y
Traceback (most recent call last):
  File "setup-dev.py", line 47, in <module>
    do_link("tune", force=args.yes)
  File "setup-dev.py", line 22, in do_link
    assert os.path.isdir(local_home), local_home
AssertionError: /home/kai/rllib/tune
`

**Comment by huixli** [comment]
Hi, looks like it's a bug in the README. Can you try not copying setup-dev.py and just `python setup-dev.py` at its original location?
