### ISSUE TITLE
how to cite it?

### ISSUE THREAD

**Issue by RayYoh** [AutodeskRoboticsLab/RLRoboticAssembly#2]
It's really a useful env, and I want to konw whether I can use it for my research?
If ok, how can I cite it?

**Comment by huixli** [comment]
Thanks and yes, you're welcome to use it for research. 
You can find the publication, on which this repo is based: https://www.sciencedirect.com/science/article/pii/S0926580521000200

**Comment by RayYoh** [comment]
thanks a lot.
